In [1]:
import numpy as np

In [7]:
a=np.random.seed(55)
a=np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [8]:
a[-1]

79

In [9]:
a[0]

56

In [10]:
a.ndim

1

In [11]:
a[19]

79

In [17]:
b=np.random.randint(20,80,(8,9))
b

array([[38, 71, 61, 37, 48, 71, 73, 71, 71],
       [75, 56, 33, 37, 67, 22, 45, 22, 57],
       [26, 35, 53, 43, 58, 73, 50, 21, 46],
       [74, 40, 69, 77, 62, 74, 43, 51, 62],
       [58, 66, 56, 59, 74, 34, 78, 59, 26],
       [40, 55, 20, 36, 70, 23, 51, 54, 43],
       [45, 61, 21, 34, 52, 59, 43, 66, 75],
       [45, 20, 22, 54, 41, 68, 35, 66, 51]])

In [16]:
b.shape

(8, 9)

In [14]:
b.ndim

2

In [18]:
b[7,0]

45

In [22]:
array[row_start: row_end : row_step , col_start: col_end:col_step]


NameError: name 'array' is not defined

In [23]:
import pandas as pd

In [36]:
x=[[5,4],[3,2],[6,4],[5,3]]
x

[[5, 4], [3, 2], [6, 4], [5, 3]]

In [37]:
t=np.array(x)
t

array([[5, 4],
       [3, 2],
       [6, 4],
       [5, 3]])

In [38]:
t.ndim

2

In [39]:
pd.Series(x)

0    [5, 4]
1    [3, 2]
2    [6, 4]
3    [5, 3]
dtype: object

In [40]:
t.ndim

2

In [41]:
pd.Series(x)

0    [5, 4]
1    [3, 2]
2    [6, 4]
3    [5, 3]
dtype: object

In [42]:
pd.DataFrame(t)

0  1
0  5  4
1  3  2
2  6  4
3  5  3

In [47]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,200,291,292])
df

name  sub
289     5    4
200     3    2
291     6    4
292     5    3

In [48]:
df.columns

Index(['name', 'sub'], dtype='object')

In [49]:
df['sub']

289    4
200    2
291    4
292    3
Name: sub, dtype: int32

In [50]:
df['sub'].mean()

3.25

In [51]:
df['sub'].median()

3.5

In [52]:
df['sub'].var()

0.9166666666666666

In [53]:
df['sub'].std()

0.9574271077563381

In [54]:
df['sub'].min()

2

In [55]:
df['sub'].max()

4

In [56]:
df['sub'].quantile(0.75)

4.0